version: "3.8"

services:
  database:
    image: mongo
    container_name: database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - "~/container_volumes/databse/data/db:/data/db"
      - "~/container_logs/databse/log:/var/log/mongodb"
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - "80:80"

  api:
    build: ./api
    container_name: api
    restart: always
    expose:
      - 8080
    volumes:
      - "~/container_logs/api/log:/var/log/wsgi"
