version: "3.8"

services:
  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - "80:80"

  mongo:
    image: mongo
    container_name: mongo
    restart: always

    volumes:
      - "~/container_volumes/mongo/data/db:/data/db"
      - "~/container_logs/mongo/log:/var/log/mongodb"

  api:
    build: ./api
    container_name: api
    restart: always
    environment:
      - FLASK_ENV=production
      - DB_NAME=filed-audio-api

    expose:
      - 8080
